### ISSUE TITLE
Question about voxel size in CAS

### ISSUE THREAD

**Issue by doublexxking** [Xharlie/Grid-GCN#1]
Thanks for your work, it is great.
I have question about the voxel size, in your down sample part, if the voxel size is too large, there is not enough number of voxel centers, that means I cannot get M points firstly.
I think the down sample will be broken in this situation? 
Am i correct or do you have some methods to solve it ?

**Comment by Xharlie** [comment]
if you check the cuda code, you can see we pass in a parameter as number of occupied voxel center.   if it's smaller than M, it's totally fine.
