### ISSUE TITLE
Question on Environmental configuration

### ISSUE THREAD

**Issue by Christinayooo** [Xharlie/Grid-GCN#3]
Hello, I'm a novice. I'm sorry to take up your time. After compiling mxnet and your gridofyop module, I was return the following error when I run the dataset:

nohup: 忽略输入
/home/christina/Grid-GCN/classification/train/../../gridifyop/additional.so
terminate called after throwing an instance of 'dmlc::Error'
  what():  [10:39:56] /home/christina/incubator-mxnet/src/runtime/registry.cc:73: Check failed: override: Global PackedFunc _Integer is already registered

I don't know what to do. I just come to you when I really can't find a solution.
By the way, in the classification section of readme, you said "refer to Pointnet", it means your program need Pointnet, or it just for comparison with your results?
Thank you very much.

**Comment by Christinayooo** [comment]
thanks,I was solved it by using mxnet1.5.0.

**Comment by sheshap** [comment]
@Christinayooo Please let us know the steps to install.
Especially the configurations
gcc version, cuda version, g++ version, cudnn version etc.,
